DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'TaxStrategy') THEN
    CREATE TYPE "TaxStrategy" AS ENUM ('NONE', 'MANUAL');
  END IF;
END
$$;

ALTER TABLE "stores"
  ADD COLUMN IF NOT EXISTS "taxEnabled" BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS "taxStrategy" "TaxStrategy" NOT NULL DEFAULT 'NONE',
  ADD COLUMN IF NOT EXISTS "defaultTaxRateBps" INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "taxShipping" BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS "pricesIncludeTax" BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS "taxOriginCountry" TEXT,
  ADD COLUMN IF NOT EXISTS "taxOriginState" TEXT,
  ADD COLUMN IF NOT EXISTS "taxOriginPostalCode" TEXT;
